<template>
    <v-row class="justify-center">
        <v-card class="max-form-width">
            <v-card-item>
                <span v-html="homeContent"></span>
            </v-card-item>
            <v-card-item v-if="errorMessage">
                <v-alert type="error" dismissible>
                    {{ errorMessage }}
                </v-alert>
            </v-card-item>
            <v-card-item>
                <h3>Configured datasets</h3>
                <v-progress-circular v-if="isLoadingDatasets" indeterminate size="24" width="3"></v-progress-circular>
                <v-alert v-else-if="datasetErrorMessage" type="error" density="compact" class="mt-2">
                    {{ datasetErrorMessage }}
                </v-alert>
                <v-list v-else-if="datasets.length" density="compact" class="mt-2 dataset-list">
                    <v-alert v-if="isLoadingDatasetKpis" type="info" density="compact" class="mb-2">
                        loading metadata KPI results...
                    </v-alert>
                    <v-list-item v-for="dataset in datasets" :key="dataset.id">
                        <v-card class="dataset-item pa-3">
                            <v-list-item-title>Metadata ID: {{ dataset.id }}</v-list-item-title>
                            <v-list-item-subtitle v-if="dataset.title">Title: {{ dataset.title }}</v-list-item-subtitle>
                            <v-list-item-subtitle v-if="dataset.description">Description: {{ dataset.description }}</v-list-item-subtitle>
                            <div class="kpi-grade-row mt-2">
                                <span class="kpi-grade-label">Metadata KPI Grade:</span>
                                <span class="kpi-grade-badge" :class="getDatasetKpiGradeClass(dataset.id)">
                                    {{ getDatasetKpiGrade(dataset.id) }}
                                </span>
                            </div>
                            <div class="mt-3 d-flex flex-wrap ga-2">
                                <v-btn
                                    size="small"
                                    color="#003DA5"
                                    variant="outlined"
                                    :loading="isLoadingKpi && selectedDatasetForKpi?.id === dataset.id"
                                    @click="showMetadataKpi(dataset)"
                                >
                                    Metadata quality assessment
                                </v-btn>
                                <v-btn size="small" color="#003DA5" variant="flat" @click="goToDatasetEditor(dataset)">
                                    Update dataset
                                </v-btn>
                            </div>
                        </v-card>
                    </v-list-item>
                </v-list>
                <v-alert v-else type="info" density="compact" class="mt-2">
                    No configured datasets found.
                </v-alert>
            </v-card-item>
        </v-card>

        <v-dialog v-model="showKpiDialog">
            <v-card>
                <v-card-title>Metadata quality assessment</v-card-title>
                <v-card-text>
                    <div>
                        Metadata ID: <strong>{{ selectedDatasetForKpi?.id }}</strong><br/>
                        Title: {{ selectedDatasetForKpi?.title || 'N/A' }}<br/>
                        Description: {{ selectedDatasetForKpi?.description || 'N/A' }}
                    </div>
                    <v-progress-circular
                        v-if="isLoadingKpi"
                        indeterminate
                        size="24"
                        width="3"
                        class="mt-4"
                    ></v-progress-circular>
                    <v-alert v-else-if="kpiErrorMessage" type="error" density="compact" class="mt-3">
                        {{ kpiErrorMessage }}
                    </v-alert>
                    <div v-else-if="kpiResult" class="mt-3">
                        <v-card variant="tonal" class="mb-3">
                            <v-card-text>
                                <div><strong>KPI Grade:</strong> {{ kpiResult.summary?.grade ?? 'N/A' }}</div>
                                <div>
                                    <strong>Score:</strong>
                                    {{ kpiResult.summary?.score ?? 'N/A' }} / {{ kpiResult.summary?.total ?? 'N/A' }}
                                </div>
                                <div><strong>Percentage:</strong> {{ formatPercentage(kpiResult.summary?.percentage) }}</div>
                                <div><strong>Generated by:</strong> {{ kpiResult.generated_by ?? 'N/A' }}</div>
                            </v-card-text>
                        </v-card>

                        <div class="text-subtitle-1 mb-2"><strong>Tests</strong></div>
                        <v-table density="compact">
                            <thead>
                                <tr>
                                    <th>Test</th>
                                    <th>Score</th>
                                    <th>Percentage</th>
                                    <th>Comments</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="test in kpiResult.tests || []" :key="test.id">
                                    <td>{{ test.title || test.id }}</td>
                                    <td>{{ test.score ?? 'N/A' }} / {{ test.total ?? 'N/A' }}</td>
                                    <td>{{ formatPercentage(test.percentage) }}</td>
                                    <td>{{ formatComments(test.comments) }}</td>
                                </tr>
                            </tbody>
                        </v-table>
                    </div>
                    <v-alert v-else type="info" density="compact" class="mt-3">
                        No KPI result available.
                    </v-alert>
                </v-card-text>
                <v-card-actions>
                    <v-spacer></v-spacer>
                    <v-btn color="#003DA5" variant="flat" @click="showKpiDialog = false">Close</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>
    </v-row>
</template>

<script setup>
import { onBeforeMount, ref } from 'vue';
import { useRouter } from 'vue-router';

const homeContent = ref('<h2>Welcome to the wis2box-webapp!</h2><br> This web-application allows you to configure datasets and stations, manually submit FM-12 SYNOP and check notifications sent by this wis2box.')

if (import.meta.env.VITE_WEBAPP_HOMEPAGE_MESSAGE != undefined) {
    homeContent.value = import.meta.env.VITE_WEBAPP_HOMEPAGE_MESSAGE;
}

const errorMessage = ref(null);
const datasets = ref([]);
const isLoadingDatasets = ref(false);
const datasetErrorMessage = ref(null);
const showKpiDialog = ref(false);
const selectedDatasetForKpi = ref(null);
const isLoadingKpi = ref(false);
const kpiErrorMessage = ref(null);
const kpiResult = ref(null);
const isLoadingDatasetKpis = ref(false);
const datasetKpiById = ref({});
const router = useRouter();

const oapiBaseUrl = `${import.meta.env.VITE_API_URL}`.replace(/\/$/, '');
const apiUrl = `${oapiBaseUrl}/collections/discovery-metadata/items?f=json`;
const kpiProcessId = 'pywcmp-wis2-wcmp2-kpi';

const sortDatasetsById = (items) => {
    return items.slice().sort((a, b) => (a.id || '').localeCompare(b.id || '', undefined, { sensitivity: 'base' }));
};

const fetchDatasets = async () => {
    isLoadingDatasets.value = true;
    datasetErrorMessage.value = null;

    try {
        const response = await fetch(apiUrl);
        if (!response.ok) {
            throw new Error(`HTTP error! Status: ${response.status}`);
        }

        const data = await response.json();
        if (data.features) {
            datasets.value = sortDatasetsById(
                data.features
                    .filter((feature) => feature.id)
                    .map((feature) => ({
                        id: feature.id,
                        title: feature.properties?.title || '',
                        description: feature.properties?.description || ''
                    }))
            );
        } else {
            datasets.value = [];
        }
    } catch (error) {
        datasetErrorMessage.value = 'Error fetching configured datasets, please check the API end point. See logs for more information.';
        console.error('Error fetching configured datasets:', error);
    } finally {
        isLoadingDatasets.value = false;
    }
};

const goToDatasetEditor = (dataset) => {
    router.push({
        name: 'DatasetEditorForm',
        query: { identifier: dataset.id }
    });
};

const formatPercentage = (value) => {
    if (value === null || value === undefined) {
        return 'N/A';
    }

    const parsed = Number(value);
    return Number.isNaN(parsed) ? 'N/A' : `${parsed.toFixed(1)}%`;
};

const formatComments = (comments) => {
    if (!Array.isArray(comments) || comments.length === 0) {
        return 'None';
    }

    return comments.join('; ');
};

const getDatasetKpiGrade = (datasetId) => {
    const summary = datasetKpiById.value[datasetId]?.summary;
    return summary?.grade ?? 'N/A';
};

const getDatasetKpiPercentage = (datasetId) => {
    const summary = datasetKpiById.value[datasetId]?.summary;
    return formatPercentage(summary?.percentage);
};

const getDatasetKpiGradeClass = (datasetId) => {
    const grade = `${getDatasetKpiGrade(datasetId) || ''}`.trim().toUpperCase();

    if (grade === 'A') {
        return 'kpi-grade-a';
    }

    if (grade === 'B' || grade === 'C') {
        return 'kpi-grade-bc';
    }

    if (grade === 'N/A' || grade === '') {
        return 'kpi-grade-na';
    }

    return 'kpi-grade-other';
};

const fetchDatasetMetadata = async (datasetId) => {
    const itemUrl = `${oapiBaseUrl}/collections/discovery-metadata/items/${encodeURIComponent(datasetId)}?f=json`;
    const response = await fetch(itemUrl, {
        headers: {
            accept: 'application/json'
        }
    });

    if (!response.ok) {
        throw new Error(`Failed to retrieve metadata record (${response.status}).`);
    }

    return response.json();
};

const executeKpiProcess = async (record) => {
    const executionUrl = `${oapiBaseUrl}/processes/${kpiProcessId}/execution`;
    const response = await fetch(executionUrl, {
        method: 'POST',
        headers: {
            accept: 'application/json',
            Prefer: 'respond-sync',
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
            inputs: {
                record
            }
        })
    });

    if (!response.ok) {
        throw new Error(`Failed to execute metadata KPI process (${response.status}).`);
    }

    return response.json();
};

const fetchMetadataKpiResult = async (datasetId) => {
    const metadataRecord = await fetchDatasetMetadata(datasetId);
    return executeKpiProcess(metadataRecord);
};

const loadAllDatasetKpis = async () => {
    if (!datasets.value.length) {
        return;
    }

    isLoadingDatasetKpis.value = true;

    try {
        const results = await Promise.allSettled(
            datasets.value.map(async (dataset) => {
                const result = await fetchMetadataKpiResult(dataset.id);
                return { id: dataset.id, result };
            })
        );

        const nextKpiById = { ...datasetKpiById.value };
        results.forEach((item) => {
            if (item.status === 'fulfilled') {
                nextKpiById[item.value.id] = item.value.result;
            }
        });
        datasetKpiById.value = nextKpiById;
    } catch (error) {
        console.error('Unexpected error while loading dataset KPI results:', error);
    } finally {
        isLoadingDatasetKpis.value = false;
    }
};

const loadMetadataKpi = async (datasetId) => {
    isLoadingKpi.value = true;
    kpiErrorMessage.value = null;
    kpiResult.value = null;

    try {
        const result = await fetchMetadataKpiResult(datasetId);
        kpiResult.value = result;
        datasetKpiById.value = {
            ...datasetKpiById.value,
            [datasetId]: result
        };
    } catch (error) {
        console.error('Error retrieving metadata KPI:', error);
        kpiErrorMessage.value = error?.message || 'Unable to retrieve metadata KPI.';
    } finally {
        isLoadingKpi.value = false;
    }
};

const showMetadataKpi = async (dataset) => {
    selectedDatasetForKpi.value = dataset;
    showKpiDialog.value = true;

    if (datasetKpiById.value[dataset.id]) {
        kpiErrorMessage.value = null;
        kpiResult.value = datasetKpiById.value[dataset.id];
        return;
    }

    await loadMetadataKpi(dataset.id);
};

// check if current URL starts with VITE_BASE_URL
const baseUrl = import.meta.env.VITE_BASE_URL || '';
if (window.location.href.startsWith(baseUrl)) {
    // If it does do not show the error message
    errorMessage.value = null;
} else {
    console.log(window.location.href);
    console.log(baseUrl);
    // If it does not show the error message
    errorMessage.value = `Please access the web application via the base URL: ${baseUrl} to avoid CORS issues.`;
    console.error(errorMessage.value);
}

onBeforeMount(async () => {
    await fetchDatasets();
    await loadAllDatasetKpis();
});

</script>

<style scoped>
.dataset-list {
    background-color: #dadada;
    padding: 4px;
    border-radius: 4px;
}

.dataset-item {
    background-color: #ffffff;
    border: 1px solid #dce3ec;
}

.kpi-grade-row {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-wrap: wrap;
}

.kpi-grade-label {
    font-size: 0.92rem;
    color: #4b5563;
}

.kpi-grade-badge {
    display: inline-block;
    min-width: 32px;
    text-align: center;
    border-radius: 999px;
    padding: 2px 10px;
    font-weight: 700;
    font-size: 0.86rem;
    color: #ffffff;
}

.kpi-grade-percentage {
    font-size: 0.86rem;
    color: #374151;
    font-weight: 600;
}

.kpi-grade-a {
    background-color: #2e7d32;
}

.kpi-grade-bc {
    background-color: #ef6c00;
}

.kpi-grade-other {
    background-color: #c62828;
}

.kpi-grade-na {
    background-color: #6b7280;
}
</style>
